### ISSUE TITLE
getData does not have correct termination condition

### ISSUE THREAD

**Issue by spock64** [publichealthengland/coronavirus-dashboard-api-javascript-sdk#2]
The termination condition in the getData loop is incorrect - calling the API with an invalid page number will result in a 404, not a 204.

The loop termination condition is when data.pagination.next is null on return from the Axios get.

**Comment by xenatisch** [comment]
It responds with a 204 when the page is invalid. The rationale is that the mandatory query parameters are still correct, so the query is valid.
